from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parent; BASE='https://www.calcuportal.com'; CATEGORY=ROOT/'blog/travel/index.html'
D={
'ooty':('Ooty','Tamil Nadu','October to June',['Ooty Lake','Government Botanical Garden','Doddabetta Peak','Ooty Rose Garden','Nilgiri Mountain Railway','tea estates']),
'kodaikanal':('Kodaikanal','Tamil Nadu','April to June and September to October',['Kodaikanal Lake',"Coaker's Walk",'Bryant Park','Pillar Rocks','Moir Point','Pine Forest']),
'goa':('Goa','Goa','November to February',['Baga Beach','Calangute Beach','Fort Aguada','Basilica of Bom Jesus','Anjuna','Palolem']),
'munnar':('Munnar','Kerala','September to May',['Mattupetty Dam','Echo Point','Tea Museum','Top Station','Kundala Lake','tea plantations'])}
BLOGS=[
('best-places-to-visit-in-ooty','Best Places to Visit in Ooty','places to visit in Ooty','ooty','Explore the best places to visit in Ooty, including lakes, gardens, viewpoints, tea estates and family-friendly attractions.','places'),
('best-time-to-visit-ooty','Best Time to Visit Ooty','best time to visit Ooty','ooty','Find the best time to visit Ooty by season, with practical tips for weather, sightseeing and trip planning.','season'),
('ooty-trip-cost','Ooty Trip Cost: Complete Budget Guide','Ooty trip cost','ooty','Estimate an Ooty trip budget for transport, hotels, food, sightseeing and local travel for different travel styles.','cost'),
('ooty-2-day-itinerary','Ooty 2-Day Itinerary: Places, Timings & Travel Tips','Ooty 2 day itinerary','ooty','Plan a practical 2-day Ooty itinerary covering major attractions without rushing between distant places.','itinerary'),
('places-to-visit-in-kodaikanal','Best Places to Visit in Kodaikanal','places to visit in Kodaikanal','kodaikanal','Explore the best places to visit in Kodaikanal, from the lake and viewpoints to parks, forests and family attractions.','places'),
('best-time-to-visit-kodaikanal','Best Time to Visit Kodaikanal','best time to visit Kodaikanal','kodaikanal','Compare Kodaikanal seasons and choose a suitable time for sightseeing, weather and outdoor activities.','season'),
('kodaikanal-trip-cost','Kodaikanal Trip Cost: Complete Budget Guide','Kodaikanal trip cost','kodaikanal','Plan a Kodaikanal travel budget with practical estimates for transport, accommodation, food and sightseeing.','cost'),
('kodaikanal-2-day-itinerary','Kodaikanal 2-Day Itinerary: A Practical Travel Plan','Kodaikanal 2 day itinerary','kodaikanal','Use this practical 2-day Kodaikanal itinerary to organise sightseeing, travel time, food breaks and viewpoints.','itinerary'),
('best-places-to-visit-in-goa','Best Places to Visit in Goa','places to visit in Goa','goa','Discover popular places to visit in Goa, including beaches, forts, heritage sites and areas for a relaxed holiday.','places'),
('best-time-to-visit-goa','Best Time to Visit Goa','best time to visit Goa','goa','Learn when to visit Goa for beaches, sightseeing, weather and different travel preferences.','season'),
('goa-trip-cost','Goa Trip Cost: Budget for 3, 5 & 7 Days','Goa trip cost','goa','Estimate Goa trip costs for 3, 5 and 7 days, including stays, food, transport and sightseeing.','cost'),
('goa-3-day-itinerary','Goa 3-Day Itinerary: Beaches, Forts & Local Travel','Goa 3 day itinerary','goa','Plan a balanced 3-day Goa itinerary with beaches, heritage attractions, food breaks and practical travel tips.','itinerary'),
('places-to-visit-in-munnar','Best Places to Visit in Munnar','places to visit in Munnar','munnar','Explore the best places to visit in Munnar, including tea plantations, lakes, dams, viewpoints and nature spots.','places'),
('best-time-to-visit-munnar','Best Time to Visit Munnar','best time to visit Munnar','munnar','Choose the best time to visit Munnar based on weather, sightseeing, greenery and road conditions.','season'),
('munnar-trip-cost','Munnar Trip Cost: Complete Budget Guide','Munnar trip cost','munnar','Estimate a Munnar trip budget for accommodation, transport, food, sightseeing and local travel.','cost'),
('kerala-trip-cost','Kerala Trip Cost: Complete Budget Guide','Kerala trip cost','munnar','Plan a Kerala trip budget with practical guidance on transport, stays, food, sightseeing and trip duration.','kerala-cost'),
('best-places-to-visit-in-kerala','Best Places to Visit in Kerala','places to visit in Kerala','munnar','Explore popular Kerala destinations and learn how to combine hill stations, beaches, backwaters and heritage stops.','kerala-places'),
('chennai-to-pondicherry-distance','Chennai to Pondicherry Distance, Route & Travel Time','Chennai to Pondicherry distance','ooty','Check the practical Chennai to Pondicherry travel distance, route options, approximate journey time and planning tips.','chennai-pondicherry'),
('bangalore-to-ooty-distance','Bangalore to Ooty Distance, Route & Travel Time','Bangalore to Ooty distance','ooty','Plan a Bangalore to Ooty road trip with route guidance, approximate travel time, stops and fuel-budget considerations.','bangalore-ooty'),
('bangalore-to-goa-distance','Bangalore to Goa Distance, Route & Travel Time','Bangalore to Goa distance','goa','Plan a Bangalore to Goa journey with route options, approximate travel time, breaks and travel-budget considerations.','bangalore-goa')]

def body(kind,d):
 n,state,best,places=d
 if kind=='places': return f'<h2>Best Places to Visit in {n}</h2><p>{n}, in {state}, is a popular destination for travellers looking for scenery, local experiences and relaxed sightseeing. A useful itinerary does not need every attraction. Pick places that fit your route and keep time for travel, meals and weather changes.</p><h2>Top Attractions</h2>'+''.join(f'<h3>{i}. {p}</h3><p>{p} is worth considering when planning a {n} trip. Check current opening hours, entry rules and local travel conditions before visiting, and allow enough time to enjoy the place.</p>' for i,p in enumerate(places,1))+f'<h2>How Many Days Are Enough?</h2><p>Two to three days is a practical starting point for a first visit to {n}. A longer stay gives you more flexibility for weather changes and slower local experiences.</p><h2>Travel Tips</h2><ul><li>Start sightseeing early where practical.</li><li>Group nearby attractions to reduce travel time.</li><li>Carry comfortable footwear and a light layer.</li><li>Keep a buffer for traffic and weather.</li></ul>'
 if kind=='season': return f'<h2>Best Time to Visit {n}</h2><p>The commonly preferred period for {n} is <strong>{best}</strong>. The right month still depends on whether you prioritise pleasant sightseeing, greenery, lower crowds or a particular activity.</p><h2>Season-by-Season Planning</h2><h3>Peak Travel Period</h3><p>Peak periods can be lively but accommodation and transport may cost more. Book popular stays early for weekends and holidays.</p><h3>Wet Weather</h3><p>Rain can change outdoor plans and road conditions. Keep the itinerary flexible and check local conditions before long drives.</p><h3>Cooler Months</h3><p>Cooler mornings and evenings can be comfortable, so layers are useful. Check visibility before planning viewpoints.</p><h2>What to Pack</h2><ul><li>Comfortable walking shoes</li><li>Light layers or a jacket</li><li>Rain protection when required</li><li>Power bank and basic medicines</li></ul>'
 if kind=='cost': return f'<h2>{n} Trip Cost: What to Budget For</h2><p>The total cost of a {n} trip depends on your starting city, duration and accommodation. Separate fixed costs such as transport and hotel bookings from flexible costs such as food, local travel and shopping.</p><h2>Main Expenses</h2><h3>Transport</h3><p>Compare bus, train, flight and private-car options using both price and travel time. For road trips, include fuel, tolls and parking.</p><h3>Accommodation</h3><p>Prices change by season, weekday and location. A convenient hotel can reduce local transport costs.</p><h3>Food</h3><p>Set a daily food allowance and include meals, snacks and drinks.</p><h3>Sightseeing</h3><p>Entry tickets, taxis, rentals and parking can add up. Group attractions by location.</p><h2>Budget Travel Tips</h2><ul><li>Compare total trip cost, not only ticket price.</li><li>Travel on weekdays when possible.</li><li>Check hotel location before booking.</li><li>Keep an emergency buffer separate from the main budget.</li></ul>'
 if kind=='itinerary': return f'<h2>{n} Itinerary</h2><p>This itinerary uses a comfortable pace so you can enjoy major attractions without spending the whole day travelling.</p><h2>Day 1</h2><p>Start with attractions close to your accommodation. Visit one major spot in the morning, take a proper lunch break and use the afternoon for another nearby attraction. Keep the evening relaxed.</p><h2>Day 2</h2><p>Begin early for a scenic attraction or viewpoint. Continue with one or two stops on the same route, then return before late evening where road conditions make night travel less convenient.</p><h2>Optional Extra Day</h2><p>Add a slower day for local food, markets, nature walks or a nearby attraction instead of creating another packed schedule.</p><h2>Planning Tips</h2><ul><li>Leave buffer time between attractions.</li><li>Check opening hours before leaving.</li><li>Keep outdoor plans flexible around weather.</li><li>Carry comfortable footwear and a light layer.</li></ul>'
 if kind=='kerala-cost': return '<h2>Kerala Trip Cost: What Determines Your Budget?</h2><p>Kerala suits short breaks and longer holidays. Your total budget changes with transport, accommodation, food, sightseeing and the number of regions you combine.</p><h2>Major Cost Heads</h2><h3>Transport</h3><p>Compare trains, buses, flights, taxis and rental cars. For multi-city trips, compare the combined time and cost.</p><h3>Hotels</h3><p>Beach areas, hill stations, cities and backwater destinations can have different pricing patterns. Location matters because long transfers add time and money.</p><h3>Food and Activities</h3><p>Keep separate allowances for meals, entry fees, boating, experiences and shopping.</p><h2>How to Save</h2><ul><li>Compare transport combinations.</li><li>Choose hotels near planned attractions.</li><li>Travel outside peak dates when practical.</li><li>Keep a separate emergency buffer.</li></ul>'
 if kind=='kerala-places': return '<h2>Best Places to Visit in Kerala</h2><p>Kerala combines hill stations, backwaters, beaches, wildlife, heritage and city experiences. The best mix depends on your available days and preferred pace.</p><h2>Popular Destination Types</h2><h3>Hill Stations</h3><p>Munnar is suited to travellers looking for tea landscapes, viewpoints and cooler weather.</p><h3>Backwaters</h3><p>Alleppey and Kumarakom are popular for backwater experiences. Check boat timings and weather before planning.</p><h3>Beaches</h3><p>Varkala and Kovalam can suit travellers looking for a slower coastal stay.</p><h3>Heritage and Cities</h3><p>Kochi works well for history, food, shopping and cultural attractions.</p><h2>How to Combine Destinations</h2><p>For a short trip, choose one region. For five to seven days, combine destinations only when the transfer time is reasonable.</p>'
 route={'chennai-pondicherry':('Chennai to Pondicherry','roughly 150 km','around 3 to 4 hours'),'bangalore-ooty':('Bangalore to Ooty','roughly 270 km','around 6 to 8 hours'),'bangalore-goa':('Bangalore to Goa','roughly 590 km','around 10 to 12 hours')}[kind]
 return f'<h2>{route[0]} Distance and Travel Time</h2><p>The practical distance depends on your exact starting point, destination area and route. Use it as an estimate rather than a promise of exact travel time.</p><h2>Approximate Journey</h2><p>The road distance is {route[1]}, while a typical road journey may take {route[2]}. Traffic, breaks, road work and weather can change the actual duration.</p><h2>Fuel Budget</h2><p>A simple estimate is <strong>fuel cost = distance ÷ vehicle mileage × fuel price</strong>. Add tolls, parking and local travel for a realistic road-trip budget.</p><h2>Road Trip Checklist</h2><ul><li>Check the live route and weather before departure.</li><li>Start early for long journeys where practical.</li><li>Plan fuel and meal breaks.</li><li>Take regular breaks on long drives.</li></ul>'

def page(slug,title,kw,d,desc,kind):
 url=f'{BASE}/blog/travel/{slug}/'; n=d[0]; qs=[(f'What is the best way to plan {n}?','Start with travel dates and budget, then choose transport, accommodation and attractions that fit your route.'),(f'How many days are enough for {n}?','Two to three days is a practical starting point for many short trips, but the ideal duration depends on your itinerary.'),(f'What should I check before travelling?','Check current weather, attraction timings, transport schedules, accommodation policies and local travel conditions.')]
 if kind=='season': qs[0]=(f'What is the best time to visit {n}?',f'A commonly preferred period is {d[2]}, although the best month depends on your travel priorities.')
 if kind.startswith('route-') or kind in ['chennai-pondicherry','bangalore-ooty','bangalore-goa']: qs=[('How accurate is the travel distance?','Distance varies by your exact starting point, route and destination address.'),('Can travel time change?','Yes. Traffic, stops, road conditions and weather can change actual journey time.'),('How should I estimate fuel cost?','Use distance divided by vehicle mileage and multiply by the current fuel price, then add tolls and parking.')]
 faq={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in qs]}
 article={'@context':'https://schema.org','@type':'Article','headline':title,'description':desc,'mainEntityOfPage':{'@type':'WebPage','@id':url},'author':{'@type':'Organization','name':'CalcuPortal'},'publisher':{'@type':'Organization','name':'CalcuPortal'}}
 faqhtml='<h2>Frequently Asked Questions</h2>'+''.join(f'<h3>{escape(q)}</h3><p>{escape(a)}</p>' for q,a in qs)
 return f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="index,follow"><title>{escape(title)} | CalcuPortal</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="{url}"><meta property="og:type" content="article"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{url}"><meta property="og:site_name" content="CalcuPortal"><meta property="og:image" content="{BASE}/logo.png"><link rel="icon" href="/favicon.png" type="image/png"><link rel="stylesheet" href="/styles.css"><script src="/script.js"></script><script type="application/ld+json">{json.dumps(article,separators=(',',':'))}</script><script type="application/ld+json">{json.dumps(faq,separators=(',',':'))}</script></head><body><header><div class="nav-container"><a href="/" class="logo"><img src="/logo.png" alt="CalcuPortal Logo" class="logo-icon"><span>CalcuPortal</span></a><nav class="nav-links"><a href="/" class="nav-link">Home</a><a href="/blog/" class="nav-link active">Blog</a><a href="/contact/" class="nav-link">Contact</a><button class="theme-btn" title="Toggle Theme"><span class="theme-btn-icon"></span></button></nav></div></header><main><article class="blog-detail"><nav class="blog-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a> › <a href="/blog/">Blog</a> › <a href="/blog/travel/">Tours &amp; Travel</a> › <span>{escape(title)}</span></nav><header class="detail-header"><h1>{escape(title)}</h1><p>{escape(desc)}</p></header><section><p>Good travel planning starts with practical details. This guide brings together useful information about timing, costs, routes and sightseeing so you can adapt the plan to your own dates and budget.</p>{body(kind,d)}<h2>Related CalcuPortal Resources</h2><p>Explore our <a href="/blog/travel/">Tours &amp; Travel guides</a> and practical <a href="/calculators/fuel-cost-calculator/">fuel cost calculator</a> when relevant to your trip.</p>{faqhtml}</section></article></main><footer><div class="copyright-bar">© <span id="year">2026</span> CalcuPortal. All rights reserved.</div></footer><script>document.getElementById('year').innerText=new Date().getFullYear();</script></body></html>'''

for slug,title,kw,key,desc,kind in BLOGS:
 out=ROOT/'blog/travel'/slug/'index.html'; out.parent.mkdir(parents=True,exist_ok=True); out.write_text(page(slug,title,kw,D[key],desc,kind),encoding='utf-8')
if CATEGORY.exists():
 text=CATEGORY.read_text(encoding='utf-8'); cards=''.join(f'<a class="blog-card" href="/blog/travel/{s}/"><div class="blog-card-body"><h3 class="blog-card-title">{escape(t)}</h3><p class="blog-card-excerpt">{escape(d)}</p><span class="blog-card-link">Read guide →</span></div></a>' for s,t,k,key,d,kind in BLOGS)
 start=text.find('<div class="article-list">'); end=text.find('</div>',start)+6
 if start>=0 and end>5: text=text[:start]+'<div class="article-list">'+cards+'</div>'+text[end:]
 CATEGORY.write_text(text,encoding='utf-8')
print(f'Generated {len(BLOGS)} travel articles.')
